# Generated by Django 4.2.26 on 2025-12-13 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_sku',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
    ]
