# Generated by Django 4.2.27 on 2026-01-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo'), ('zalopay', 'Ví ZaloPay'), ('card', 'Thẻ Visa/Mastercard/JCB'), ('vnpay', 'VNPay')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
