# Generated by Django 4.2.27 on 2026-01-06 05:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('jcb', 'JCB')], max_length=20, verbose_name='Loại thẻ')),
                ('masked_number', models.CharField(max_length=19, verbose_name='Số thẻ đã che')),
                ('last_four', models.CharField(max_length=4, verbose_name='4 số cuối')),
                ('cardholder_name', models.CharField(max_length=100, verbose_name='Tên chủ thẻ')),
                ('expiry_month', models.PositiveSmallIntegerField(verbose_name='Tháng hết hạn')),
                ('expiry_year', models.PositiveSmallIntegerField(verbose_name='Năm hết hạn')),
                ('is_default', models.BooleanField(default=False, verbose_name='Thẻ mặc định')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Đã hết hạn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thẻ đã lưu',
                'verbose_name_plural': 'Thẻ đã lưu',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có định dạng: '0xxxxxxxxx' hoặc '+84xxxxxxxxx'", regex='^(0|\\+84)[0-9]{9,10}$')], verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('is_social_account', models.BooleanField(default=False, verbose_name='Tài khoản Social')),
                ('social_provider', models.CharField(blank=True, max_length=20, verbose_name='Nhà cung cấp Social')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên người nhận')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có định dạng: '0xxxxxxxxx' hoặc '+84xxxxxxxxx'", regex='^(0|\\+84)[0-9]{9,10}$')], verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ chi tiết')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('province_code', models.CharField(max_length=10, verbose_name='Mã tỉnh/thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('district_code', models.CharField(max_length=10, verbose_name='Mã quận/huyện')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('ward_code', models.CharField(blank=True, max_length=10, verbose_name='Mã phường/xã')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=20, verbose_name='Nhà cung cấp')),
                ('provider_email', models.EmailField(max_length=254, verbose_name='Email từ nhà cung cấp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tài khoản Social',
                'verbose_name_plural': 'Tài khoản Social',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
