# Generated by Django 4.2.27 on 2026-01-05 09:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city_code',
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='0123456789', max_length=15, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có định dạng: '0xxxxxxxxx' hoặc '+84xxxxxxxxx'", regex='^(0|\\+84)[0-9]{9,10}$')], verbose_name='Số điện thoại'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='Tỉnh/Thành phố'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='province_code',
            field=models.CharField(default='', max_length=10, verbose_name='Mã tỉnh/thành phố'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_social_account',
            field=models.BooleanField(default=False, verbose_name='Tài khoản Social'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_provider',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nhà cung cấp Social'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ chi tiết'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100, verbose_name='Quận/Huyện'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district_code',
            field=models.CharField(max_length=10, verbose_name='Mã quận/huyện'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=150, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('jcb', 'JCB')], max_length=20, verbose_name='Loại thẻ')),
                ('masked_number', models.CharField(max_length=19, verbose_name='Số thẻ đã che')),
                ('last_four', models.CharField(max_length=4, verbose_name='4 số cuối')),
                ('cardholder_name', models.CharField(max_length=100, verbose_name='Tên chủ thẻ')),
                ('expiry_month', models.PositiveSmallIntegerField(verbose_name='Tháng hết hạn')),
                ('expiry_year', models.PositiveSmallIntegerField(verbose_name='Năm hết hạn')),
                ('is_default', models.BooleanField(default=False, verbose_name='Thẻ mặc định')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Đã hết hạn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thẻ đã lưu',
                'verbose_name_plural': 'Thẻ đã lưu',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=20, verbose_name='Nhà cung cấp')),
                ('provider_email', models.EmailField(max_length=254, verbose_name='Email từ nhà cung cấp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tài khoản Social',
                'verbose_name_plural': 'Tài khoản Social',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
