# Generated by Django 4.2.27 on 2026-01-18 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_visitors', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thống kê ngày',
                'verbose_name_plural': 'Thống kê ngày',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='Từ khóa')),
                ('results_count', models.IntegerField(default=0, verbose_name='Số kết quả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử tìm kiếm',
                'verbose_name_plural': 'Lịch sử tìm kiếm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('step', models.CharField(choices=[('view_product', 'Xem sản phẩm'), ('add_to_cart', 'Thêm vào giỏ'), ('view_cart', 'Xem giỏ hàng'), ('checkout', 'Thanh toán'), ('complete', 'Hoàn thành')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sự kiện Funnel',
                'verbose_name_plural': 'Sự kiện Funnel',
                'indexes': [models.Index(fields=['session_id', 'step'], name='analytics_f_session_52fd73_idx'), models.Index(fields=['created_at'], name='analytics_f_created_13cd9c_idx')],
            },
        ),
    ]
