# Generated by Django 4.2.27 on 2026-01-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('ghn', 'Giao Hàng Nhanh'), ('ghtk', 'Giao Hàng Tiết Kiệm'), ('viettel_post', 'Viettel Post'), ('vnpost', 'VN Post')], max_length=20, unique=True, verbose_name='Đơn vị vận chuyển')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mặc định')),
                ('api_token', models.CharField(blank=True, max_length=200, verbose_name='API Token')),
                ('shop_id', models.CharField(blank=True, max_length=100, verbose_name='Shop ID')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Cấu hình')),
            ],
            options={
                'verbose_name': 'Cấu hình vận chuyển',
                'verbose_name_plural': 'Cấu hình vận chuyển',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('ghn', 'Giao Hàng Nhanh'), ('ghtk', 'Giao Hàng Tiết Kiệm'), ('viettel_post', 'Viettel Post'), ('vnpost', 'VN Post')], max_length=20, verbose_name='Đơn vị vận chuyển')),
                ('tracking_code', models.CharField(max_length=100, unique=True, verbose_name='Mã vận đơn')),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Phí vận chuyển')),
                ('status', models.CharField(choices=[('pending', 'Chờ lấy hàng'), ('picked_up', 'Đã lấy hàng'), ('in_transit', 'Đang vận chuyển'), ('out_for_delivery', 'Đang giao'), ('delivered', 'Đã giao'), ('failed', 'Giao thất bại'), ('returned', 'Hoàn hàng')], default='pending', max_length=50, verbose_name='Trạng thái')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Dự kiến giao')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Thực tế giao')),
                ('weight', models.IntegerField(default=0, verbose_name='Khối lượng (gram)')),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền thu hộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Vận đơn',
                'verbose_name_plural': 'Vận đơn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('ghn', 'Giao Hàng Nhanh'), ('ghtk', 'Giao Hàng Tiết Kiệm'), ('viettel_post', 'Viettel Post'), ('vnpost', 'VN Post')], max_length=20, verbose_name='Đơn vị')),
                ('from_province', models.CharField(max_length=100, verbose_name='Tỉnh gửi')),
                ('to_province', models.CharField(max_length=100, verbose_name='Tỉnh nhận')),
                ('weight_from', models.IntegerField(verbose_name='Từ (gram)')),
                ('weight_to', models.IntegerField(verbose_name='Đến (gram)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá')),
            ],
            options={
                'verbose_name': 'Bảng giá vận chuyển',
                'verbose_name_plural': 'Bảng giá vận chuyển',
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Trạng thái')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Vị trí')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('timestamp', models.DateTimeField(verbose_name='Thời gian')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu gốc')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='shipping.shipment', verbose_name='Vận đơn')),
            ],
            options={
                'verbose_name': 'Lịch sử vận chuyển',
                'verbose_name_plural': 'Lịch sử vận chuyển',
                'ordering': ['-timestamp'],
            },
        ),
    ]
