# Generated by Django 4.2.27 on 2025-12-24 06:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(
                    choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')],
                    validators=[django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá sao')),
                ('comment', models.TextField(verbose_name='Nội dung đánh giá')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Tích cực'), ('negative', 'Tiêu cực'),
                                                                    ('neutral', 'Trung lập')], max_length=10,
                                               verbose_name='Cảm xúc')),
                ('sentiment_score', models.FloatField(default=0,
                                                      validators=[django.core.validators.MinValueValidator(-1),
                                                                  django.core.validators.MaxValueValidator(1)],
                                                      verbose_name='Điểm sentiment')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Hình ảnh 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Hình ảnh 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Hình ảnh 3')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Đã duyệt')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Mua hàng xác thực')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Lượt hữu ích')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    related_name='review', to='orders.orderitem',
                                                    verbose_name='Sản phẩm đã mua')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                              to='products.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                           to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user', 'order_item')},
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes',
                                             to='reviews.review', verbose_name='Đánh giá')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes',
                                           to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phiếu hữu ích',
                'verbose_name_plural': 'Phiếu hữu ích',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
