# Generated by Django 4.2.26 on 2025-12-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='processed_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
