# Generated by Django 4.2.27 on 2026-01-06 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='Session ID')),
                ('activity_type', models.CharField(choices=[('view', 'Xem sản phẩm'), ('add_to_cart', 'Thêm vào giỏ'), ('purchase', 'Mua hàng'), ('wishlist', 'Thêm wishlist'), ('search', 'Tìm kiếm')], max_length=50, verbose_name='Loại hoạt động')),
                ('search_query', models.CharField(blank=True, max_length=200, verbose_name='Từ khóa tìm kiếm')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Hoạt động người dùng',
                'verbose_name_plural': 'Hoạt động người dùng',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='recommendat_user_id_c1cdba_idx'), models.Index(fields=['product', 'activity_type'], name='recommendat_product_f1af7d_idx'), models.Index(fields=['created_at'], name='recommendat_created_d0cb2f_idx'), models.Index(fields=['session_id'], name='recommendat_session_dc1910_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Giá trị từ 0.0 (không tương đồng) đến 1.0 (rất tương đồng)', verbose_name='Điểm tương đồng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='products.product', verbose_name='Sản phẩm')),
                ('similar_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='products.product', verbose_name='Sản phẩm tương tự')),
            ],
            options={
                'verbose_name': 'Độ tương đồng sản phẩm',
                'verbose_name_plural': 'Độ tương đồng sản phẩm',
                'ordering': ['-score'],
                'unique_together': {('product', 'similar_product')},
            },
        ),
        migrations.CreateModel(
            name='FrequentlyBoughtTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, help_text='Số lần 2 sản phẩm xuất hiện trong cùng đơn hàng', verbose_name='Số lần mua cùng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_together', to='products.product', verbose_name='Sản phẩm')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_with', to='products.product', verbose_name='Sản phẩm mua kèm')),
            ],
            options={
                'verbose_name': 'Sản phẩm mua kèm',
                'verbose_name_plural': 'Sản phẩm mua kèm',
                'ordering': ['-count'],
                'unique_together': {('product', 'related_product')},
            },
        ),
    ]
