# Generated by Django 4.2.27 on 2026-01-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(choices=[('VCB', 'Vietcombank'), ('TCB', 'Techcombank'), ('MB', 'MB Bank'), ('ACB', 'ACB'), ('VPB', 'VPBank'), ('TPB', 'TPBank'), ('BIDV', 'BIDV'), ('VTB', 'VietinBank'), ('STB', 'Sacombank'), ('HDB', 'HDBank'), ('MSB', 'MSB'), ('OCB', 'OCB'), ('SHB', 'SHB'), ('EIB', 'Eximbank'), ('NAB', 'Nam A Bank')], max_length=20, verbose_name='Mã ngân hàng')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Tên ngân hàng')),
                ('account_number', models.CharField(max_length=30, verbose_name='Số tài khoản')),
                ('account_name', models.CharField(max_length=100, verbose_name='Tên tài khoản')),
                ('branch', models.CharField(blank=True, max_length=200, verbose_name='Chi nhánh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tài khoản ngân hàng',
                'verbose_name_plural': 'Tài khoản ngân hàng',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EWalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('momo', 'MoMo'), ('zalopay', 'ZaloPay')], max_length=20, verbose_name='Loại ví')),
                ('wallet_id', models.CharField(max_length=50, verbose_name='ID ví / Số điện thoại')),
                ('wallet_name', models.CharField(max_length=100, verbose_name='Tên chủ ví')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Ví điện tử',
                'verbose_name_plural': 'Ví điện tử',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('vnpay', 'VNPay'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('bank_transfer', 'Chuyển khoản')], max_length=20, verbose_name='Phương thức')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Mã giao dịch')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('response_code', models.CharField(blank=True, max_length=50, verbose_name='Mã phản hồi')),
                ('response_message', models.TextField(blank=True, verbose_name='Thông báo')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu phản hồi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Giao dịch thanh toán',
                'verbose_name_plural': 'Giao dịch thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền hoàn')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('refund_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch hoàn')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymenttransaction', verbose_name='Giao dịch gốc')),
            ],
            options={
                'verbose_name': 'Hoàn tiền',
                'verbose_name_plural': 'Hoàn tiền',
            },
        ),
    ]
