# Generated by Django 4.2.27 on 2026-01-20 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order_updates', models.BooleanField(default=True, verbose_name='Email cập nhật đơn hàng')),
                ('email_promotions', models.BooleanField(default=True, verbose_name='Email khuyến mãi')),
                ('email_wishlist', models.BooleanField(default=True, verbose_name='Email wishlist giảm giá')),
                ('email_newsletter', models.BooleanField(default=False, verbose_name='Email bản tin')),
                ('email_account', models.BooleanField(default=True, verbose_name='Email tài khoản (bảo mật)')),
                ('push_order_updates', models.BooleanField(default=True, verbose_name='Push cập nhật đơn hàng')),
                ('push_promotions', models.BooleanField(default=True, verbose_name='Push khuyến mãi')),
                ('push_wishlist', models.BooleanField(default=True, verbose_name='Push wishlist giảm giá')),
                ('push_chat', models.BooleanField(default=True, verbose_name='Push chat hỗ trợ')),
                ('push_flash_sale', models.BooleanField(default=True, verbose_name='Push flash sale')),
                ('push_delivery', models.BooleanField(default=True, verbose_name='Push giao hàng')),
                ('sms_order_confirmation', models.BooleanField(default=False, verbose_name='SMS xác nhận đơn hàng')),
                ('sms_delivery', models.BooleanField(default=False, verbose_name='SMS giao hàng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tùy chọn thông báo',
                'verbose_name_plural': 'Tùy chọn thông báo',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=190, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=200, verbose_name='P256DH Key')),
                ('auth', models.CharField(max_length=100, verbose_name='Auth Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Lần sử dụng cuối')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đăng ký Push',
                'verbose_name_plural': 'Đăng ký Push',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_1159a5_idx')],
                'unique_together': {('user', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order', 'Đơn hàng'), ('promotion', 'Khuyến mãi'), ('wishlist', 'Wishlist'), ('system', 'Hệ thống'), ('chat', 'Chat')], max_length=50, verbose_name='Loại thông báo')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bổ sung')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày đọc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
